### ISSUE TITLE
Vue.js

### ISSUE THREAD

**Issue by purepear** [colonjs/colon#1]
Is this a Vue fork? Vue template engine copy? Cause if it is... you should mention it.

**Comment by dabanlee** [comment]
Thank you for reminding me. I have added the relevant mention, but `colon` is not a Vue fork, just directives syntax similarity, and a small number of [snippets](https://github.com/colonjs/colon/blob/master/src/compile/parse.js#L4-L25) of reference.

**Comment by vinayakkulkarni** [comment]
lmao :P
